<MDLabelBtn>
    text_size: self.width, None
    height: self.texture_size[1]
    padding: 10, 10
    size_hint_y: None
    halign: "center"
    font_size: 32

<Header>:
    MDBoxLayout:
        orientation: 'horizontal'
        spacing: 5
        size_hint_y: None
        height: 30

        Button:
            id: main
            size_hint_y: None
            pos_hint: {"center_x": 0.5}
            height: 30
            font_size: 22
            text: "Main Screen"
            background_color: 1.8, 1.8, 1.8, 1
            on_press: root.parent.parent.goto_main()  # parent.parent - wierd call to screen class...

        Button:
            id: imageview
            size_hint_y: None
            pos_hint: {"center_x": 0.5}
            height: 30
            font_size: 22
            text: "Image Screen"
            background_color: 1.8, 1.8, 1.8, 1
            on_press: root.parent.parent.goto_images()

        Button:
            id: dbview
            size_hint_y: None
            pos_hint: {"center_x": 0.5}
            height: 30
            font_size: 22
            text: "DB Screen"
            background_color: 1.8, 1.8, 1.8, 1
            on_press: root.parent.parent.goto_db()

        Button:
            id: mlview
            size_hint_y: None
            pos_hint: {"center_x": 0.5}
            height: 30
            font_size: 22
            text: "ML Screen"
            background_color: 1.8, 1.8, 1.8, 1
            on_press: root.parent.parent.goto_ml()

        Button:
            id: detectionview
            size_hint_y: None
            pos_hint: {"center_x": 0.5}
            height: 30
            font_size: 22
            text: "Detection"
            background_color: 1.8, 1.8, 1.8, 1
            on_press: root.parent.parent.goto_detection()

        ImageMDButton:
            id: settingsview
            source: 'settings.png'
            size_hint_x: None
            width: dp(30)
            height: dp(30)
            pos_hint: {"center_y": 0.5}

            on_press: root.parent.parent.goto_settings()

            allow_stretch: True
            keep_ratio: True
            allow_hover: True

            canvas.before:
                Color:
                    rgba: 1, 1, 1, .18
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
