<ImageViewScreen>
    MDBoxLayout:
        orientation:'vertical'

        Header:
            id: header
            size_hint: 1, None
            height: 36

        AppScreenCard:
            size_hint: 1, 1
            orientation: 'vertical'
            padding: [12, 6, 12, 6]
            spacing: 6

            MDBoxLayout:
                orientation: 'vertical'
                size_hint_y: 0.92

                MDLabel:
                    id: load_label
                    halign: 'center'
                    font_size: 28
                    text: "Loading, please wait..."
                    size_hint_y: None
                    height: 32

                ProgressBar:
                    id: progress_bar
                    value: 0
                    min: 0
                    max: 100
                    pos_hint: {'center_x': 0.5}
                    size_hint: 0.8, None
                    height: 16

                MDLabel:
                    id: current_folder
                    text: ""
                    halign: "center"
                    font_size: 15
                    size_hint_y: None
                    height: 22

                ScrollView:
                    size_hint_y: 1
                    do_scroll_x: False
                    do_scroll_y: True
                    scroll_wheel_distance: 60

                    GridLayout:
                        id: grid
                        cols: 3
                        size: (root.width, root.height)
                        size_hint: None, None
                        height: self.minimum_height
                        row_default_height: 250
                        spacing: 8
                        padding: 4

            MDBoxLayout:
                orientation:'horizontal'
                size_hint_y: None
                height: 38
                spacing: 8

                AppActionButton:
                    id: choose_image
                    size_hint_x: 0.28
                    text: 'Choose image source'
                    on_press: root.file_chooser_popup()

                AppActionButton:
                    id: to_db_simple_btn
                    size_hint_x: 0.18
                    text: 'To DB (simple)'
                    on_press: root.save_img_to_db(enc=False)
                    disabled: True

                AppActionButton:
                    id: to_db_protect_btn
                    size_hint_x: 0.18
                    text: 'To DB (protect)'
                    on_press: root.save_img_to_db(enc=True)
                    disabled: True

                AppActionButton:
                    id: to_ml_btn
                    size_hint_x: 0.14
                    text: 'To ML'
                    on_press: root.save_img_to_ml()
                    disabled: True

                AppActionButton:
                    id: select_unselect_action_button
                    size_hint_x: 0.14
                    text: 'Select All'
                    on_press: root.select_or_unselect_button_action()

                MDLabel:
                    id: selected_images
                    size_hint_x: 0.18
                    text: "Selected: 0"
                    font_size: 18
                    halign: 'center'
