<ImageViewScreen>
    MDBoxLayout:
        orientation:'vertical'

        Header:
            id: header
            size_hint: 1, None
            height: 30

        MDBoxLayout:
            orientation: 'vertical'

            MDLabel:
                id: load_label
                halign: 'center'
                font_size: 36
                text: "Loading, please wait..."
                size_hint_y: .1

            ProgressBar:
                id: progress_bar
                value: 0
                min: 0
                max: 100
                pos_hint: {'x': .1}
                size_hint: .8, .1

            MDLabel:
                id: current_folder
                text: ""
                halign: "center"
                font_size: 16
                size_hint_y: None
                height: 24

            ScrollView:
                size_hint_y: .9
                pos_hint: {'x': 0, 'y': 0}
                do_scroll_x: False
                do_scroll_y: True
                scroll_wheel_distance: 60

                GridLayout:
                    id: grid
                    cols: 3
                    size:(root.width, root.height)
                    size_hint: None, None
                    height: self.minimum_height
                    row_default_height: 250

        MDBoxLayout:
            orientation:'horizontal'
            size_hint_y: None
            height: 40

            Button:
                id: choose_image
                size_hint_x: 0.4
                text: 'Choose image source'
                background_color: (1, 1, 1, .5)
                on_press: root.file_chooser_popup()

            Button:
                id: to_db_simple_btn
                size_hint_x: 0.3
                text: 'To DB (simple)'
                background_color: (1, 1, 1, .5)
                on_press: root.save_img_to_db(enc=False)
                disabled: True

            Button:
                id: to_db_protect_btn
                size_hint_x: 0.3
                text: 'To DB (protect)'
                background_color: (1, 1, 1, .5)
                on_press: root.save_img_to_db(enc=True)
                disabled: True

            Button:
                id: to_ml_btn
                size_hint_x: 0.3
                text: 'To ML'
                background_color: (1, 1, 1, .5)
                on_press: root.save_img_to_ml()
                disabled: True

            Button:
                id: select_unselect_action_button
                size_hint_x: 0.25
                text: 'Select All'
                background_color: (1, 1, 1, .5)
                on_press: root.select_or_unselect_button_action()

            MDLabel:
                size_hint_x: 0.3
                id: selected_images
                text: "Selected: 0"
                font_size: 28
                halign: 'center'
                size_hint_x: 0.5
