<LoadingScreen>
    MDCard:
        style: "outlined"
        focus_behavior: False
        ripple_behavior: False
        size_hint: None, None
        size: 400, 300
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        padding: 25
        spacing: 25
        radius: [16, 16, 16, 16]
        line_color: (1, 1, 1, 0.15)
        orientation: 'vertical'

        MDLabel:
            id: word_label
            text: "Loading, please wait..."
            font_size: 32
            halign: 'center'
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            height: self.texture_size[1]
            size_hint_y: .8
            padding: [0, 15]

        ProgressBar:
            id: pbar

        MDLabel:
            id: status
            text: "Module Kivy init"
            font_size: 22
            halign: 'center'
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            height: self.texture_size[1]
            size_hint_y: .2
            padding: [0, 15]
