<LoginScreen>
    MDCard:
        style: "outlined"
        focus_behavior: False
        ripple_behavior: False
        size_hint: None, None
        size: 400, 300
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        padding: 25
        spacing: 25
        radius: [16, 16, 16, 16]
        line_color: (1, 1, 1, 0.15)
        orientation: 'vertical'

        MDLabel:
            id: word_label
            text: "Enter a password."
            font_size: 32
            halign: 'center'
            size_hint_y: None
            height: self.texture_size[1]
            padding: [0, 15]

        MDTextField:
            id: word_input
            mode: "filled"
            size_hint_x: None
            width: 250
            font_size: 24
            password: True
            pos_hint: {"center_x": 0.5}
            on_text_validate:
                root.submit()

            MDTextFieldHintText:
                text: "password"

        MDButton:
            id: login
            style: "outlined"
            pos_hint: {"center_x": 0.5}
            on_press:
                root.submit()

            MDButtonText:
                id: login_text
                text: "Login"
                font_size: 20

        Widget:
            size_hint_y: None
            height: 10
