<MainScreen>
    MDBoxLayout:
        orientation:'vertical'

        Header:
            id: header
            size_hint: 1, None
            height: 30

        MDBoxLayout:
            size_hint: 1, 0.025

        MDCard:
            style: "outlined"
            focus_behavior: False
            ripple_behavior: False
            state_hover: 0
            state_press: 0
            state_drag: 0
            size_hint: 0.95, 0.95
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            padding: 20
            spacing: 20
            radius: [16, 16, 16, 16]
            line_color: (1, 1, 1, 0.12)
            orientation: 'vertical'

            MDLabel:
                id: word_label
                text: "Enter new text:"
                font_size: 32
                halign: 'center'
                size_hint_y: None
                height: self.texture_size[1]

            ScrollView:
                id: scroll
                do_scroll_x: False
                do_scroll_y: True
                size_hint_y: 1

                canvas.before:
                    Color:
                        rgba: 1, 1, 1, 0.1
                    RoundedRectangle:
                        radius: [20, 20, 20, 20]
                        pos: self.pos
                        size: self.size

            MDTextField:
                id: word_input
                multiline: False
                mode: "filled"
                font_size: 28
                size_hint_x: 0.8
                pos_hint: {"center_x": 0.5}
                on_text_validate: root.submit()

                MDTextFieldHintText:
                    text: "Enter text:"

            MDBoxLayout:
                orientation: 'horizontal'
                size_hint_y: None
                height: 40

                FloatLayout:
                    size_hint: 1, 1

                    MDGridLayout:
                        cols: 5
                        spacing: 5
                        size_hint_x: None
                        width: self.minimum_width
                        pos_hint: {"center_x": 0.5, "center_y": 0.5}

                        MDButton:
                            id: text_submit
                            style: "outlined"
                            on_press: root.submit()
                            disabled: True
                            MDButtonText:
                                text: "Submit"
                                font_size: 22

                        MDButton:
                            id: text_delete
                            style: "outlined"
                            on_press: root.delete_record()
                            disabled: True
                            MDButtonText:
                                text: "Delete Record"
                                font_size: 22

                        MDButton:
                            id: text_update
                            style: "outlined"
                            on_press: root.update_record()
                            disabled: True
                            MDButtonText:
                                text: "Update Record"
                                font_size: 22

                        MDButton:
                            id: url_open
                            style: "outlined"
                            on_press: root.open_url()
                            MDButtonText:
                                text: "Open Url"
                                font_size: 22

                        ImageMDButton:
                            source: 'app/resources/icons/reload.png'
                            size_hint: None, None
                            size: dp(40), dp(40)
                            pos_hint: {"center_x": 0.5, "center_y": 0.5}

                            on_press: root.reload_records()

                            fit_mode: "contain"
                            allow_hover: True

                            canvas.before:
                                Color:
                                    rgba: 1, 1, 1, .18
                                RoundedRectangle:
                                    pos: self.pos
                                    size: self.size

        MDBoxLayout:
            size_hint: 1, 0.025 # Spacer
