<SettingsViewScreen>
    MDBoxLayout:
        orientation: 'vertical'

        Header:
            id: header
            size_hint: 1, None
            height: 36

        MDBoxLayout:
            size_hint: 1, 0.02

        AppScreenCard:
            size_hint: 0.96, 0.95
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            orientation: 'vertical'

            MDLabel:
                halign: 'center'
                font_size: 26
                text: "Application Settings"
                size_hint_y: None
                height: 40

            ScrollView:
                size_hint_y: 1
                do_scroll_x: False
                do_scroll_y: True
                scroll_wheel_distance: 40

                GridLayout:
                    id: grid
                    cols: 1
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: 8
                    padding: [12, 12]
                    row_default_height: 44

            MDBoxLayout:
                orientation:'horizontal'
                size_hint_y: None
                height: 40
                spacing: 12

                AppActionButton:
                    text: "Apply"
                    size_hint_x: 0.33
                    on_press: root.apply_changes()

                AppActionButton:
                    text: "Reload"
                    size_hint_x: 0.33
                    on_press: root.reload_records()

                AppActionButton:
                    text: "Reset Defaults"
                    size_hint_x: 0.33
                    on_press: root.reset_settings()

        MDBoxLayout:
            size_hint: 1, 0.02
