<SettingsViewScreen>
    MDBoxLayout:
        orientation: 'vertical'

        Header:
            id: header
            size_hint: 1, None
            height: 30

        MDBoxLayout:
            orientation: 'vertical'

            MDLabel:
                halign: 'center'
                font_size: 32
                text: "Application Settings"
                size_hint_y: .05

            ScrollView:
                size_hint_y: 1
                do_scroll_x: False
                do_scroll_y: True
                scroll_wheel_distance: 40

                GridLayout:
                    id: grid
                    cols: 2
                    size_hint_y: None
                    height: self.minimum_height
                    width: self.parent.width
                    row_default_height: 40

            MDBoxLayout:
                orientation:'horizontal'
                size_hint_y: None
                height: 40

                Button:
                    text: "Apply"
                    size_hint_x: 0.3
                    background_color: (1, 1, 1, .5)
                    on_press: root.apply_changes()

                Button:
                    text: "Reload"
                    size_hint_x: 0.3
                    background_color: (1, 1, 1, .5)
                    on_press: root.reload_records()

                Button:
                    text: "Reset"
                    size_hint_x: 0.3
                    background_color: (1, 1, 1, .5)
                    on_press: root.reset_settings()
