<SettingsViewScreen>
    MDBoxLayout:
        orientation:'vertical'

        Header:
            id: header
            size_hint: 1, None
            height: 30

        MDBoxLayout:
            orientation: 'vertical'

            MDLabel:
                halign: 'center'
                font_size: 32
                text: "Application Settings"
                size_hint_y: .05

            ScrollView:
                size_hint_y: 1
                do_scroll_x: False
                do_scroll_y: True
                scroll_wheel_distance: 40

                GridLayout:
                    id: grid
                    cols: 2
                    size_hint_y: None
                    height: self.minimum_height
                    width: self.parent.width
                    row_default_height: 40

                    Label:
                        text: "Setting Name 1"
                        size_hint_y: None
                        height: self.texture_size[1]
                    MDTextField:
                        hint_text: "Value 1"
                        mode: "rectangle"
                        size_hint_y: None
                        height: 50
